

Profiles:

    TwoOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *hyc
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *chenman
                    - *lixingxing
                    - *Org3
                    - *Org4
                    - *Org5
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *chenman
                - *lixingxing
                - *Org3
                - *Org4
                - *Org5

Organizations:

    - &hyc
        Name: hycMSP
        ID: hycMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

    - &chenman
        Name: chenmanMSP
        ID: chenmanMSP

        MSPDir: crypto-config/peerOrganizations/chenman.example.com/msp

        AnchorPeers:
            - Host: peer0.chenman.example.com
              Port: 7051

    - &lixingxing
        Name: lixingxingMSP
        ID: lixingxingMSP

        MSPDir: crypto-config/peerOrganizations/lixingxing.example.com/msp

        AnchorPeers:
            - Host: peer0.lixingxing.example.com
              Port: 7051

    - &Org3
        Name: Org3MSP
        ID: Org3MSP

        MSPDir: crypto-config/peerOrganizations/org3.example.com/msp

        AnchorPeers:
            - Host: peer0.org3.example.com
              Port: 7051

    - &Org4
        Name: Org4MSP
        ID: Org4MSP

        MSPDir: crypto-config/peerOrganizations/org4.example.com/msp

        AnchorPeers:
            - Host: peer0.org4.example.com
              Port: 7051

    - &Org5
        Name: Org5MSP
        ID: Org5MSP

        MSPDir: crypto-config/peerOrganizations/org5.example.com/msp

        AnchorPeers:
            - Host: peer0.org5.example.com
              Port: 7051

Orderer: &OrdererDefaults

    OrdererType: kafka

    Addresses:
        - hyc0.example.com:7050
        - hyc1.example.com:7050
        - hyc2.example.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 98 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 192.168.56.109:9092
            - 192.168.56.111:9092
            - 192.168.56.110:9092
            - 192.168.56.113:9092

    Organizations:

Application: &ApplicationDefaults

    Organizations:

Capabilities:
    Global: &ChannelCapabilities
        V1_1: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_1: true