# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"

  ca:
    container_name: ca
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.chenman.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c2bc9a64ab5b7ac6e3075aab965b7a380302d804732a29dde605af1e5c4f73b4_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.chenman.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c2bc9a64ab5b7ac6e3075aab965b7a380302d804732a29dde605af1e5c4f73b4_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/chenman.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  peer0.chenman.example.com:
    container_name: peer0.chenman.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=192.168.56.115:5984

      - CORE_PEER_ID=peer0.chenman.example.com
      - CORE_PEER_NETWORKID=fabric_kafka
      - CORE_PEER_ADDRESS=peer0.chenman.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.chenman.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.chenman.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.chenman.example.com:7051
      - CORE_PEER_LOCALMSPID=chenmanMSP

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_kafka_default
      - CORE_VM_DOCKER_TLS_ENABLED=false
      # - CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/chaincode/go
        - ./crypto-config/peerOrganizations/chenman.example.com/peers/peer0.chenman.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/chenman.example.com/peers/peer0.chenman.example.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - couchdb
    networks:
      default:
        aliases:
          - fabric_kafka
    extra_hosts:
     - "hyc0.example.com:192.168.0.107"
     - "hyc1.example.com:192.168.56.114"
     - "hyc2.example.com:192.168.56.116"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.chenman.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.chenman.example.com:7052
      - CORE_PEER_LOCALMSPID=chenmanMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chenman.example.com/peers/peer0.chenman.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chenman.example.com/peers/peer0.chenman.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chenman.example.com/peers/peer0.chenman.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chenman.example.com/users/Admin@chenman.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.chenman.example.com
    extra_hosts:
     - "hyc0.example.com:192.168.0.107"
     - "hyc1.example.com:192.168.56.114"
     - "hyc2.example.com:192.168.56.116"
     - "peer0.chenman.example.com:192.168.56.115"
